sudo: false
language: ruby

before_install: gem update --system
before_script: bundle update

script: script/cibuild

matrix:
  fast_finish: true
  include:
    - rvm: 2.6.1
    - rvm: 2.5.3
    - rvm: 2.4.5
    - rvm: 2.3.8
    # JRuby
    # - rvm: jruby-9.1.16.0 - https://github.com/kacperduras/jekyll-w2m/issues/2

notfications:
  email: false
